apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-configmap
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  DEVELOPMENT: {{ quote .Values.app.development }}
  APP_PORT: {{ quote .Values.app.port }}