{{ if .Values.app.local -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "app.fullname" . }}-local-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{ end -}}
